import Config
  # Configuración de PostgreSQL para autenticación (Render)

config :prettycore, Prettycore.PsqlRepo,
  hostname: System.get_env("DB_HOSTNAME_PSQL", "localhost"),
  port: String.to_integer(System.get_env("DB_PORT_PSQL", "5432")),
  username: System.get_env("DB_USERNAME_PSQL", "postgres"),
  password: System.get_env("DB_PASSWORD_PSQL", "postgres"),
  database: System.get_env("DB_NAME_PSQL", "prettycore"),
  ssl: false,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  idle_interval: 4_000,      # ping SQL cada 4s — Render cierra SSL idle ~10min pero con NAT puede ser menos
  queue_target: 5_000,
  queue_interval: 2_000,
  connect_timeout: 30_000,
  socket_options: [keepalive: true],  # TCP keepalive a nivel OS, previene drops silenciosos de NAT/firewall
  parameters: [client_encoding: "UTF8"]


# SMTP Configuration for Hostinger
config :prettycore, Prettycore.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: "smtp.hostinger.com",
  username: "servicio.cliente@ennovacore.com.mx",
  password: System.get_env("SMTP_PASSWORD") || "MegaCore.1",
  ssl: false,
  tls: :always,
  tls_options: [
    verify: :verify_none,
    versions: [:"tlsv1.2", :"tlsv1.3"]
  ],
  auth: :always,
  port: 587,
  retries: 2,
  timeout: 15_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :prettycore, PrettycoreWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:prettycore, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:prettycore, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :prettycore, PrettycoreWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/prettycore_web_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :prettycore, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# SMTP no necesita API client HTTP
config :swoosh, :api_client, false
